services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: relygate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MySecurePassword123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d relygate"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    environment:
      NODE_ENV: development
      PG_DB_HOST: postgres
      PG_DB_PORT: 5432
      PG_DB_NAME: relygate
      PG_DB_USER: postgres
      PG_DB_PASSWORD: MySecurePassword123
      JWT_SECRET: supersecretjwtkey-change-in-production
      PORT: 3333
    ports:
      - "3333:3333"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - app_uploads:/app/uploads
    restart: unless-stopped

volumes:
  postgres_data:
  app_uploads: