-- Table: LoginUser
CREATE TABLE IF NOT EXISTS LoginUser (
    LoginID SERIAL PRIMARY KEY,
    TenantID int,
    IsActive char(1),
    RoleAccessID int,
    RoleName varchar(250),
    FirstN varchar(100),
    MiddleN varchar(100),
    LastN varchar(100),
    UserName varchar(250) NOT NULL,
    Passwrd varchar(1000) NOT NULL,
    DisplayN varchar(250),
    Email varchar(150),
    Mobile varchar(50),
    MobileSecondary varchar(50),
    PhotoFlag char(10),
    PhotoPath varchar(1000),
    Photo varchar(450),
    LastLogin timestamp,
    LastPasswrdChgedDate timestamp,
    SharedLogin char(10),
    LoginIP varchar(250),
    LinkFlatFlag char(1),
    LinkeFlatID varchar(250),
    LinkeFlatName varchar(450),
    Custom_1 varchar(50),
    Custom_2 varchar(50),
    CreatedDate timestamp,
    UpdatedDate timestamp,
    CreatedBy varchar(250),
    UpdatedBy varchar(250)
);
